apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
    - name: http
      port: 11434        # external LB port
      targetPort: 11434  # port inside the pod
